### ISSUE TITLE
Replace readline

### ISSUE THREAD

**Issue by scphantm** [clarkperkins/click-shell#3]
Please consider replacing 'readline' with 'pyreadline'.  The problem is on some systems (mainly cygwin) it attempts to pull down the readline lib and compile it as an install.  As of yet, I havn't figured out why readline won't compile on a cygwin machine, gave up trying quite honestly because i had work to do and just stripped click-shell out of the app.  But pyreadline is supposed to be feature for feature the same thing and pure python.  Take a look and if you can swap it out, probably worth it.

**Comment by clarkperkins** [comment]
So `pyreadline` doesn't work on macOS, it's windows only.

Instead, I'll drop the dependency on `readline` since python includes it by default on some systems, and I'll try to import `pyreadline` in the case where `readline`can't be imported.  If neither `readline` nor `pyreadline` are available, you just won't have completion in shell mode.

**Comment by clarkperkins** [comment]
@scphantm if you don't mind, could you try out #5 to see if it works for your use case?  If you don't want to clone & install, you can try this:  `pip install https://github.com/clarkperkins/click-shell/archive/bugfix/no-readline.tar.gz && pip install pyreadline`

**Comment by clarkperkins** [comment]
@scphantm I'm going to close this for now.  Feel free to re-open or create a new issue if your problem isn't solved.
